<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit( 1 );
}

/**
 * Meta generated by editing or runtime sync should be recreated remotely.
 */
function barbados_push_post_excluded_meta_keys() {
	return array(
		'_edit_lock',
		'_edit_last',
		'_gutenberg_lab_villa_availability_sync_status',
		// The scaffold ID is local import provenance, not a live post relationship.
		'_gutenberg_lab_villa_import_source_villa',
	);
}

/**
 * Rewrites URLs throughout nested post meta and block attributes.
 */
function barbados_push_post_rewrite_value( $value, $from_url, $to_url ) {
	if ( is_array( $value ) ) {
		foreach ( $value as $key => $item ) {
			$value[ $key ] = barbados_push_post_rewrite_value( $item, $from_url, $to_url );
		}

		return $value;
	}

	return is_string( $value ) ? str_replace( $from_url, $to_url, $value ) : $value;
}

/**
 * Finds attachment IDs and linked post IDs used by supported Gutenberg blocks.
 */
function barbados_push_post_collect_block_dependencies( $blocks, &$attachment_ids, &$post_ids ) {
	foreach ( $blocks as $block ) {
		$attributes = isset( $block['attrs'] ) && is_array( $block['attrs'] ) ? $block['attrs'] : array();

		foreach ( array( 'imageId', 'posterImageId', 'mediaId' ) as $key ) {
			if ( isset( $attributes[ $key ] ) && is_numeric( $attributes[ $key ] ) ) {
				$attachment_ids[] = (int) $attributes[ $key ];
			}
		}

		if ( 'core/image' === ( $block['blockName'] ?? '' ) && ! empty( $attributes['id'] ) ) {
			$attachment_ids[] = (int) $attributes['id'];
		}

		if ( 'core/gallery' === ( $block['blockName'] ?? '' ) && ! empty( $attributes['ids'] ) && is_array( $attributes['ids'] ) ) {
			$attachment_ids = array_merge( $attachment_ids, array_map( 'intval', $attributes['ids'] ) );
		}

		if ( 'gutenberg-lab-blocks/card-grid' === ( $block['blockName'] ?? '' ) && ! empty( $attributes['selectedVillaIds'] ) ) {
			$post_ids = array_merge( $post_ids, array_map( 'intval', $attributes['selectedVillaIds'] ) );
		}

		if ( 'contact-form-7/contact-form-selector' === ( $block['blockName'] ?? '' ) && ! empty( $attributes['id'] ) ) {
			$post_ids[] = (int) $attributes['id'];
		}

		if ( ! empty( $block['innerBlocks'] ) ) {
			barbados_push_post_collect_block_dependencies( $block['innerBlocks'], $attachment_ids, $post_ids );
		}
	}
}

/**
 * Collects upload paths embedded in post content and meta.
 */
function barbados_push_post_collect_upload_paths( $value, &$upload_paths ) {
	if ( is_array( $value ) ) {
		foreach ( $value as $item ) {
			barbados_push_post_collect_upload_paths( $item, $upload_paths );
		}

		return;
	}

	if ( ! is_string( $value ) ) {
		return;
	}

	preg_match_all( '#https?://[^\s"\'<>]+/wp-content/uploads/([^\s"\'<>?]+)#i', $value, $matches );

	foreach ( $matches[1] as $path ) {
		$upload_paths[] = rawurldecode( html_entity_decode( $path, ENT_QUOTES | ENT_HTML5, 'UTF-8' ) );
	}
}

/**
 * Creates a portable representation of one WordPress post.
 */
function barbados_push_post_build_package( $post_id, $from_url, $to_url ) {
	$post = get_post( $post_id );

	if ( ! $post ) {
		WP_CLI::error( sprintf( 'Post %d does not exist.', $post_id ) );
	}

	$author = get_userdata( $post->post_author );
	$meta   = get_post_meta( $post_id );

	// Fetching every meta key at once returns raw database values. Normalize
	// them before JSON export so WordPress serializes arrays exactly once remotely.
	foreach ( $meta as $meta_key => $values ) {
		$meta[ $meta_key ] = array_map( 'maybe_unserialize', $values );
	}

	foreach ( barbados_push_post_excluded_meta_keys() as $excluded_key ) {
		unset( $meta[ $excluded_key ] );
	}

	$terms = array();
	foreach ( get_object_taxonomies( $post->post_type ) as $taxonomy ) {
		$assigned_terms = wp_get_object_terms( $post_id, $taxonomy );

		if ( is_wp_error( $assigned_terms ) ) {
			WP_CLI::error( $assigned_terms->get_error_message() );
		}

		$terms[ $taxonomy ] = array_map(
			static function ( $term ) {
				return array(
					'name' => $term->name,
					'slug' => $term->slug,
				);
			},
			$assigned_terms
		);
	}

	$post_data = array(
		'post_type'         => $post->post_type,
		'post_title'        => $post->post_title,
		'post_name'         => $post->post_name,
		'post_content'      => $post->post_content,
		'post_excerpt'      => $post->post_excerpt,
		'post_status'       => $post->post_status,
		'post_password'     => $post->post_password,
		'post_date'         => $post->post_date,
		'post_date_gmt'     => $post->post_date_gmt,
		'comment_status'    => $post->comment_status,
		'ping_status'       => $post->ping_status,
		'menu_order'        => (int) $post->menu_order,
		'post_author_login' => $author ? $author->user_login : '',
	);

	$post_data = barbados_push_post_rewrite_value( $post_data, $from_url, $to_url );
	$meta      = barbados_push_post_rewrite_value( $meta, $from_url, $to_url );

	$attachment_ids = array();
	$post_ids       = array();
	barbados_push_post_collect_block_dependencies( parse_blocks( $post_data['post_content'] ), $attachment_ids, $post_ids );

	if ( ! empty( $meta['_thumbnail_id'][0] ) ) {
		$attachment_ids[] = (int) $meta['_thumbnail_id'][0];
	}

	$attachments = array();
	foreach ( array_unique( array_filter( $attachment_ids ) ) as $attachment_id ) {
		$attachment = get_post( $attachment_id );
		$attachments[] = array(
			'id'            => $attachment_id,
			'post_type'     => $attachment ? $attachment->post_type : '',
			'attached_file' => (string) get_post_meta( $attachment_id, '_wp_attached_file', true ),
		);
	}

	$linked_posts = array();
	foreach ( array_unique( array_filter( $post_ids ) ) as $linked_post_id ) {
		$linked_post = get_post( $linked_post_id );
		$linked_posts[] = array(
			'id'        => $linked_post_id,
			'post_type' => $linked_post ? $linked_post->post_type : '',
			'slug'      => $linked_post ? $linked_post->post_name : '',
			'title'     => $linked_post ? $linked_post->post_title : '',
		);
	}

	$upload_paths = array();
	barbados_push_post_collect_upload_paths( array( $post_data, $meta ), $upload_paths );

	return array(
		'schema_version' => 1,
		'exported_at'    => gmdate( 'c' ),
		'source_post_id' => (int) $post_id,
		'post'           => $post_data,
		'meta'           => $meta,
		'terms'          => $terms,
		'dependencies'   => array(
			'attachments' => $attachments,
			'posts'       => $linked_posts,
			'uploads'     => array_values( array_unique( array_filter( $upload_paths ) ) ),
		),
		'content_hash'   => hash( 'sha256', $post_data['post_content'] ),
	);
}

/**
 * Reads and validates a transfer package.
 */
function barbados_push_post_read_package( $data_file ) {
	if ( ! $data_file || ! is_readable( $data_file ) ) {
		WP_CLI::error( 'The post transfer package is missing or unreadable.' );
	}

	$data = json_decode( file_get_contents( $data_file ), true );

	if ( ! is_array( $data ) || 1 !== ( $data['schema_version'] ?? 0 ) || empty( $data['post']['post_name'] ) ) {
		WP_CLI::error( 'The post transfer package is invalid.' );
	}

	return $data;
}

/**
 * Refuses a push that would create broken media or cross-post references.
 */
function barbados_push_post_check_dependencies( $data ) {
	$errors = array();

	foreach ( $data['dependencies']['attachments'] as $dependency ) {
		$remote = get_post( $dependency['id'] );
		$file   = (string) get_post_meta( $dependency['id'], '_wp_attached_file', true );

		if ( ! $remote || 'attachment' !== $remote->post_type || $file !== $dependency['attached_file'] ) {
			$errors[] = sprintf( 'Attachment %d does not match production (%s).', $dependency['id'], $dependency['attached_file'] );
		}
	}

	foreach ( $data['dependencies']['posts'] as $dependency ) {
		$remote = get_post( $dependency['id'] );

		if ( ! $remote || $remote->post_type !== $dependency['post_type'] || $remote->post_name !== $dependency['slug'] ) {
			$errors[] = sprintf( 'Linked post %d does not match production (%s).', $dependency['id'], $dependency['title'] );
		}
	}

	foreach ( $data['dependencies']['uploads'] as $relative_path ) {
		if ( ! is_file( WP_CONTENT_DIR . '/uploads/' . ltrim( $relative_path, '/' ) ) ) {
			$errors[] = sprintf( 'Upload is missing on production: %s', $relative_path );
		}
	}

	if ( $errors ) {
		WP_CLI::error( "Dependency check failed:\n- " . implode( "\n- ", $errors ) );
	}

	$existing = get_page_by_path( $data['post']['post_name'], OBJECT, $data['post']['post_type'] );

	return array(
		'action'      => $existing ? 'update' : 'create',
		'remote_id'   => $existing ? (int) $existing->ID : null,
		'attachments' => count( $data['dependencies']['attachments'] ),
		'linked_posts' => count( $data['dependencies']['posts'] ),
		'uploads'     => count( $data['dependencies']['uploads'] ),
	);
}

/**
 * Creates or updates one remote post, drafting it until all data is in place.
 */
function barbados_push_post_import_package( $data, $backup_dir, $target_status ) {
	$allowed_statuses = array( 'draft', 'publish' );
	if ( ! in_array( $target_status, $allowed_statuses, true ) ) {
		WP_CLI::error( 'Target status must be draft or publish.' );
	}

	$check    = barbados_push_post_check_dependencies( $data );
	$existing = get_page_by_path( $data['post']['post_name'], OBJECT, $data['post']['post_type'] );
	$backup   = '';

	if ( $existing ) {
		if ( ! wp_mkdir_p( $backup_dir ) && ! is_dir( $backup_dir ) ) {
			WP_CLI::error( sprintf( 'Could not create the post backup directory: %s', $backup_dir ) );
		}

		$backup = trailingslashit( $backup_dir ) . sprintf(
			'post-%d-%s-%s.json',
			$existing->ID,
			sanitize_file_name( $existing->post_name ),
			gmdate( 'Ymd-His' )
		);
		$backup_data = barbados_push_post_build_package( $existing->ID, home_url(), home_url() );
		$backup_json = wp_json_encode( $backup_data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );

		if ( false === file_put_contents( $backup, $backup_json ) || ! is_file( $backup ) || 0 === filesize( $backup ) ) {
			WP_CLI::error( sprintf( 'Could not write the production post backup: %s', $backup ) );
		}
	}

	$post       = $data['post'];
	$author     = $post['post_author_login'] ? get_user_by( 'login', $post['post_author_login'] ) : false;
	$post_array = array(
		'ID'             => $existing ? $existing->ID : 0,
		'post_type'      => $post['post_type'],
		'post_title'     => $post['post_title'],
		'post_name'      => $post['post_name'],
		'post_content'   => $post['post_content'],
		'post_excerpt'   => $post['post_excerpt'],
		'post_status'    => 'draft',
		'post_password'  => $post['post_password'],
		'comment_status' => $post['comment_status'],
		'ping_status'    => $post['ping_status'],
		'menu_order'     => (int) $post['menu_order'],
		'post_author'    => $author ? (int) $author->ID : 1,
	);

	if ( ! $existing ) {
		$post_array['post_date']     = $post['post_date'];
		$post_array['post_date_gmt'] = $post['post_date_gmt'];
	}

	$post_id = wp_insert_post( wp_slash( $post_array ), true );
	if ( is_wp_error( $post_id ) ) {
		WP_CLI::error( $post_id->get_error_message() );
	}

	foreach ( array_keys( get_post_meta( $post_id ) ) as $meta_key ) {
		delete_post_meta( $post_id, $meta_key );
	}

	foreach ( $data['meta'] as $meta_key => $values ) {
		foreach ( $values as $value ) {
			add_post_meta( $post_id, $meta_key, $value );
		}
	}

	foreach ( $data['terms'] as $taxonomy => $terms ) {
		$term_ids = array();

		foreach ( $terms as $term_data ) {
			$term = term_exists( $term_data['slug'], $taxonomy );
			if ( ! $term ) {
				$term = wp_insert_term( $term_data['name'], $taxonomy, array( 'slug' => $term_data['slug'] ) );
			}

			if ( is_wp_error( $term ) ) {
				WP_CLI::error( $term->get_error_message() );
			}

			$term_ids[] = (int) ( is_array( $term ) ? $term['term_id'] : $term );
		}

		wp_set_object_terms( $post_id, $term_ids, $taxonomy, false );
	}

	if ( hash( 'sha256', get_post_field( 'post_content', $post_id ) ) !== $data['content_hash'] ) {
		WP_CLI::error( 'Remote content hash differs from the transfer package.' );
	}

	if ( get_post_field( 'post_password', $post_id ) !== $post['post_password'] ) {
		WP_CLI::error( 'Remote post password differs from the transfer package.' );
	}

	foreach ( $data['meta'] as $meta_key => $values ) {
		$stored_values = array_map( 'maybe_unserialize', get_post_meta( $post_id, $meta_key, false ) );

		if ( serialize( $stored_values ) !== serialize( $values ) ) {
			WP_CLI::error( sprintf( 'Remote meta verification failed for %s.', $meta_key ) );
		}
	}

	foreach ( $data['terms'] as $taxonomy => $terms ) {
		$expected_slugs = wp_list_pluck( $terms, 'slug' );
		$stored_slugs   = wp_get_object_terms( $post_id, $taxonomy, array( 'fields' => 'slugs' ) );

		if ( is_wp_error( $stored_slugs ) ) {
			WP_CLI::error( $stored_slugs->get_error_message() );
		}

		sort( $expected_slugs );
		sort( $stored_slugs );

		if ( $expected_slugs !== $stored_slugs ) {
			WP_CLI::error( sprintf( 'Remote taxonomy verification failed for %s.', $taxonomy ) );
		}
	}

	// The record stays a draft until content, meta, and terms all verify.
	$status_result = wp_update_post( array( 'ID' => $post_id, 'post_status' => $target_status ), true );
	if ( is_wp_error( $status_result ) ) {
		WP_CLI::error( $status_result->get_error_message() );
	}

	$availability = null;
	if ( 'villa' === $post['post_type'] && function_exists( 'gutenberg_lab_blocks_sync_villa_availability' ) && get_post_meta( $post_id, '_gutenberg_lab_villa_ical_feeds', true ) ) {
		$availability = gutenberg_lab_blocks_sync_villa_availability( $post_id );
	}

	return array(
		'action'       => $check['action'],
		'ID'           => (int) $post_id,
		'title'        => get_the_title( $post_id ),
		'status'       => get_post_status( $post_id ),
		'password_set' => '' !== (string) get_post_field( 'post_password', $post_id ),
		'backup'       => $backup,
		'permalink'    => get_permalink( $post_id ),
		'availability' => $availability,
	);
}

$mode = $args[0] ?? '';

if ( 'export' === $mode ) {
	$post_id  = isset( $args[1] ) ? (int) $args[1] : 0;
	$out_file = $args[2] ?? '';
	$from_url = isset( $args[3] ) ? untrailingslashit( $args[3] ) : '';
	$to_url   = isset( $args[4] ) ? untrailingslashit( $args[4] ) : '';
	$data     = barbados_push_post_build_package( $post_id, $from_url, $to_url );

	if ( ! $out_file || false === file_put_contents( $out_file, wp_json_encode( $data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES ) ) ) {
		WP_CLI::error( 'Could not write the post transfer package.' );
	}

	WP_CLI::success( sprintf( 'Exported post %d with %d meta keys.', $post_id, count( $data['meta'] ) ) );
	exit;
}

if ( 'check' === $mode ) {
	$data = barbados_push_post_read_package( $args[1] ?? '' );
	WP_CLI::line( wp_json_encode( barbados_push_post_check_dependencies( $data ) ) );
	exit;
}

if ( 'import' === $mode ) {
	$data = barbados_push_post_read_package( $args[1] ?? '' );
	WP_CLI::line( wp_json_encode( barbados_push_post_import_package( $data, $args[2] ?? '', $args[3] ?? 'draft' ) ) );
	exit;
}

WP_CLI::error( 'Use export, check, or import mode.' );
